version: 0.2


phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y postgresql-client
      - export POSTGRES_HOST="geostore-database-1.ck0fw0ou3xwc.us-east-2.rds.amazonaws.com"
      - export POSTGRES_PORT="5432"
      - export POSTGRES_DATABASE="postgres"
      - export POSTGRES_USERNAME="geostore"
      - export POSTGRES_PASSWORD="Christian97"
      - PGPASSWORD="$POSTGRES_PASSWORD" psql -t -A \ -h "$POSTGRES_HOST" \ -p "$POSTGRES_PORT" \ -d "$POSTGRES_DATABASE" \ -U "$POSTGRES_USERNAME" \

      - createdb geostore
      - psql -U geostore -d geostore -f ./doc/sql/002_create_schema_postgres.sql
      - psql -U geostore_test -d geostore -f ./doc/sql/002_create_schema_postgres.sql

      - apt-get install -y maven
      - cd src
      - mvn clean install -Dovrdir=postgres -Ppostgresgi
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      #- docker login –u User –p $LOGIN_PASSWORD
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn clean install
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
  
artifacts:
  files:
    - appspec.yml
    - scripts/*
    - src/target/*
    - src/web/app/target/*
  name: geostore-artifact
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
